<a href="https://colab.research.google.com/github/gyuwonchoi/PytorchTutorial/blob/main/Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import torch 
import numpy as np 

### 텐서 초기화

In [7]:
data=[[1, 2],[3, 4]]
x_data=torch.tensor(data)

print(x_data[:,0]) # dimension changed 

tensor([1, 3])


In [17]:
np_array=np.array(data) # tensor to numpy : colab does not show " , " 
x_np = torch.from_numpy(np_array) # numpy to tensor

In [21]:
x_ones = torch.ones_like(x_data) # remain the x_data's attribute
print(f"Ones Tensor:\n{x_ones}")

x_rand = torch.rand_like(x_data, dtype=torch.float) # declare the data type
print(f"Random Tensor: \n {x_rand}\n")

Ones Tensor:
tensor([[1, 1],
        [1, 1]])
Random Tensor: 
 tensor([[0.2815, 0.1094],
        [0.7352, 0.3927]])



### Shape은 텐서의 dimension을 나타내는 튜플로, 출력 텐서의 차원을 결정

In [3]:
shape = (2,3, )

rand_tensor=torch.rand(shape)
print(rand_tensor)

ones_tensor=torch.ones(shape)
print(ones_tensor)

zero_tensor=torch.zeros(shape)
print(zero_tensor)

tensor([[0.0132, 0.3912, 0.9280],
        [0.6625, 0.8137, 0.7683]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


### Attribute of Tensor

In [3]:
tensor=torch.rand(3,4)

print(tensor)
print(f"shape of tensor:{tensor.shape}")
print(f"dtpye of tensor:{tensor.dtype}")
print(f"device of tensor:{tensor.device}")

tensor([[0.8897, 0.5819, 0.5262, 0.5289],
        [0.5568, 0.8922, 0.2944, 0.0324],
        [0.9185, 0.8345, 0.7642, 0.6277]])
shape of tensor:torch.Size([3, 4])
dtpye of tensor:torch.float32
device of tensor:cpu


### Operation of Tensor
##### .to :GPU로 텐서를 명시적 이동

In [5]:
if torch.cuda.is_available():
  tensor=tensor.to("cuda")

In [10]:
tensor=torch.ones(4,4)

print(tensor)
print(f"{tensor[0]}") # first row
print(f"{tensor[:, 0]}") # first column
print(f"{tensor[..., -1]}") # last column

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([1., 1., 1., 1.])
tensor([1., 1., 1., 1.])
tensor([1., 1., 1., 1.])


In [11]:
tensor[:, 1] =0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [17]:
# torch.act
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

# torch.stack 
t2 = torch.stack([tensor, tensor, tensor])
print(t2)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])
tensor([[[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]]])


In [20]:
y1= tensor @ tensor.T
y2 = tensor.matmul(tensor.T) # tensor matmul takes 1 argument 

print(y1)
print(y2)

y3 = torch.rand_like(y1) # size define
torch.matmul(tensor, tensor.T, out=y3) # torch argument takes 3

print(y3)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


In [23]:
z1 = tensor * tensor
print(z1)

z2 = tensor.mul(tensor)
print(z2)

z3 = torch.rand_like(z1)
z3 = torch.mul(tensor, tensor, out=z3)
print(z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


### Single-element Tensor : Aggregate(하나로 집계) == 요소가 하나인 Tensor


In [25]:
agg=tensor.sum()
agg_item=agg.item() 

print(agg_item)

12.0


### In-place 연산

In [27]:
print(f"{tensor}")
tensor.add_(5) # add() Adds a scalar or tensor to self tensor. 
               # _는 operand:피연산자를 바꿔치기 : tensor 업데이트 안했는데 바뀜
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


###Numpy 변환

In [30]:
t= torch.ones(5)
print(f"t:{t}")

n= t.numpy()
print(n)

t:tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [31]:
# 넘파이를 텐서로

n= np.ones(5)
t= torch.from_numpy(n)

print(n)

[1. 1. 1. 1. 1.]
